# Generated by Django 2.2.3 on 2019-08-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0101_auto_20190719_0839"),
        ("product", "0096_product_minimal_variant_price"),
    ]

    operations = []
